web:
  image: nginx:latest
  ports:
    - "8000:80"
  volumes:
    - ./:/var/www/app
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:8-fpm
  volumes:
    - ./:/var/www/app